import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faRulerCombined } from "@fortawesome/free-solid-svg-icons";

export const propertyImages = [
    {
      id:1,
      src: ["/property-1.jpg","/property-2.jpg", "/property-3.jpg", "/property-4.jpg", "/property-5.jpg", ],
      alt: "property 1",
      type: "Flat",
      price: "₹16,500",
      rentType: "Flat 2 BHK",
      location: "Dwarka, Delhi, India",
      scale: <FontAwesomeIcon icon={faRulerCombined} />,
      size: "950 Sqft",
      style: "Furnished",
      quantity: "2 Bath",
    },
    {
      id:2,
      src: ["/property-2.jpg", "/property-2.jpg", "/property-3.jpg", "/property-4.jpg", "/property-5.jpg",],
      alt: "property 2",
      type: "PG",
      price: "₹8000",
      rentType: "Girls PG",
      location: "Janakpuri, Delhi, India",
      scale: <FontAwesomeIcon icon={faRulerCombined} />,
      size: "1000 Sqft",
      style: "2 Bed",
      quantity: "1 Bath",
    },
    {
      id:3,
      src: ["/property-3.jpg", "/property-2.jpg", "/property-3.jpg", "/property-4.jpg", "/property-5.jpg",],
      alt: "property 3",
      type: "PG",
      price: "₹9500",
      rentType: "Boys Pg",
      location: "Sector 62, Noida, India",
      scale: <FontAwesomeIcon icon={faRulerCombined} />,
      size: "850 Sqft",
      style: "1 Bed",
      quantity: "1 Bath",
    },
    {
      id:4,
      src: ["/property-4.jpg", "/property-2.jpg", "/property-3.jpg", "/property-4.jpg", "/property-5.jpg",],
      alt: "property 4",
      type: "PG",
      price: "₹12,345",
      rentType: "Coliving PG",
      location: "Sector 137, Noida, India",
      scale: <FontAwesomeIcon icon={faRulerCombined} />,
      size: "900 Sqft",
      style: "3 Bed",
      quantity: "2 Bath",
    },
    {
      id:5,
      src: ["/property-5.jpg", "/property-2.jpg", "/property-3.jpg", "/property-4.jpg", "/property-5.jpg",],
      alt: "property 5",
      type: "Flat",
      price: "₹12,500",
      rentType: "Flat 3 BHK",
      location: "Sector 14, Gurgaon, India",
      scale: <FontAwesomeIcon icon={faRulerCombined} />,
      size: "1000 Sqft",
      style: "Unfurnished",
      quantity: "2 Bath",
    },
    {
      id:6,
      src: ["/property-6.jpg", "/property-2.jpg", "/property-3.jpg", "/property-4.jpg", "/property-5.jpg",],
      alt: "property 6",
      type: "PG",
      price: "₹12,000",
      rentType: "Boys PG Near Sector 18",
      location: "Sector 18, Noida, India",
      scale: <FontAwesomeIcon icon={faRulerCombined} />,
      size: "1100 Sqft",
      style: "4 Bed",
      quantity: "2 Bath",
    },
    {
      id:7,
      src: ["/property-6.jpg", "/property-2.jpg", "/property-3.jpg", "/property-4.jpg", "/property-5.jpg",],
      alt: "property 6",
      type: "PG",
      price: "₹12,000",
      rentType: "Boys PG Near Sector 18",
      location: "Sector 18, Noida, India",
      scale: <FontAwesomeIcon icon={faRulerCombined} />,
      size: "1100 Sqft",
      style: "4 Bed",
      quantity: "2 Bath",
    },
    {
      id:8,
      src: ["/property-6.jpg", "/property-2.jpg", "/property-3.jpg", "/property-4.jpg", "/property-5.jpg",],
      alt: "property 6",
      type: "PG",
      price: "₹12,000",
      rentType: "Boys PG Near Sector 18",
      location: "Sector 18, Noida, India",
      scale: <FontAwesomeIcon icon={faRulerCombined} />,
      size: "1100 Sqft",
      style: "4 Bed",
      quantity: "2 Bath",
    },
    {
      id:9,
      src: ["/property-6.jpg", "/property-2.jpg", "/property-3.jpg", "/property-4.jpg", "/property-5.jpg",],
      alt: "property 6",
      type: "PG",
      price: "₹12,000",
      rentType: "Boys PG Near Sector 18",
      location: "Sector 18, Noida, India",
      scale: <FontAwesomeIcon icon={faRulerCombined} />,
      size: "1100 Sqft",
      style: "4 Bed",
      quantity: "2 Bath",
    },
    {
      id:10,
      src: ["/property-6.jpg", "/property-2.jpg", "/property-3.jpg", "/property-4.jpg", "/property-5.jpg",],
      alt: "property 6",
      type: "PG",
      price: "₹12,000",
      rentType: "Boys PG Near Sector 18",
      location: "Sector 18, Noida, India",
      scale: <FontAwesomeIcon icon={faRulerCombined} />,
      size: "1100 Sqft",
      style: "4 Bed",
      quantity: "2 Bath",
    },
    {
      id:11,
      src: ["/property-6.jpg","/property-2.jpg", "/property-3.jpg", "/property-4.jpg", "/property-5.jpg",],
      alt: "property 6",
      type: "PG",
      price: "₹12,000",
      rentType: "Boys PG Near Sector 18",
      location: "Sector 18, Noida, India",
      scale: <FontAwesomeIcon icon={faRulerCombined} />,
      size: "1100 Sqft",
      style: "4 Bed",
      quantity: "2 Bath",
    },
    {
      id:12,
      src: ["/property-6.jpg", "/property-2.jpg", "/property-3.jpg", "/property-4.jpg", "/property-5.jpg",],
      alt: "property 6",
      type: "PG",
      price: "₹12,000",
      rentType: "Boys PG Near Sector 18",
      location: "Sector 18, Noida, India",
      scale: <FontAwesomeIcon icon={faRulerCombined} />,
      size: "1100 Sqft",
      style: "4 Bed",
      quantity: "2 Bath",
    },
   
  ];